#!/usr/bin/env python
#
#  Author: Sean Reifschneider <sean+opensource@realgo.com>
#  Date: Sun Nov 10, 2013

import sys
import dtar

password = 'TEST_PASSWORD'


dtar.filter_tar(sys.stdin, sys.stdout, '/dev/shm/test.bs', password,
                verbose=True)
