#!/usr/bin/env python
#
#  Author: Sean Reifschneider <sean+opensource@realgo.com>
#  Date: Sun Nov 10, 2013

import sys
import dtar


def main():
    args = dtar.parse_args()
    try:
        config = dtar.load_config_file(args.config_file)
        password = dtar.get_password(args)

        if not password:
            if 'password' in config:
                password = config['password']
            if 'keyfile' in config:
                with open(config['keyfile'], 'r') as fp:
                    password = fp.read()

        if not password:
            raise ValueError(
                'No password specified in config file or command-line')
    except ValueError as e:
        dtar.error(e.message)

    dtar.filter_tar(sys.stdin, sys.stdout, '/dev/shm/test.bs', password,
                    verbose=args.verbose)

if __name__ == '__main__':
    main()
