#!/usr/bin/env python
#
#  Author: Sean Reifschneider <sean+opensource@realgo.com>
#  Date: Sun Nov 10, 2013

import sys
import dtar


def open_args(args):
    if args.in_file and args.in_file != '-':
        in_fp = open(args.in_file, 'rb')
    else:
        in_fp = sys.stdin
    if args.out_file and args.out_file != '-':
        out_fp = open(args.out_file, 'wb')
    else:
        out_fp = sys.stdout

    return in_fp, out_fp


def create(args, password):
    in_fp, out_fp = open_args(args)
    dtar.filter_tar(
        in_fp, out_fp, args.blockstore_directory, password,
        verbose=args.verbose)


def list(args, password):
    in_fp, out_fp = open_args(args)
    dtar.list_dtar(
        in_fp, out_fp, args.blockstore_directory, password,
        verbose=args.verbose)


def main():
    args = dtar.parse_args()
    try:
        config = dtar.load_config_file(args.config_file)
        password = dtar.get_password(args)

        if not password:
            if 'password' in config:
                password = config['password']
            if 'keyfile' in config:
                with open(config['keyfile'], 'r') as fp:
                    password = fp.read()

        if not password:
            raise ValueError(
                'No password specified in config file or command-line')
    except ValueError as e:
        dtar.error(e.message)

    if args.command == 'create':
        create(args, password)
    if args.command == 'list':
        list(args, password)

if __name__ == '__main__':
    main()
