#!/usr/bin/env python
#
#  Author: Sean Reifschneider <sean+opensource@realgo.com>
#  Date: Sun Nov 10, 2013

import sys
import tarzan


def open_args(args):
    if args.in_file and args.in_file != '-':
        in_fp = open(args.in_file, 'rb')
    else:
        in_fp = sys.stdin
    if args.out_file and args.out_file != '-':
        out_fp = open(args.out_file, 'wb')
    else:
        out_fp = sys.stdout

    return in_fp, out_fp


def do_genkey(args, config):
    if args.keyfile is None:
        sys.stderr.write(
            'ERROR: No keyfile specified in config file or on command-line.\n')
        sys.exit(1)
    key = tarzan.TarzanPublicKey(args.keyfile)
    key.generate_new_key()
    key.write_key()

    key = tarzan.TarzanPublicKey(args.keyfile)
    key.read_key()


def do_create(args, config):
    in_fp, out_fp = open_args(args)
    tarzan.filter_tar(
        in_fp, out_fp, args.blockstore_directory, password)


def do_decrypt(args, config):
    in_fp, out_fp = open_args(args)
    tarzan.decrypt_tarzan(
        in_fp, out_fp, args.blockstore_directory, password)


def do_list(args, config):
    in_fp, out_fp = open_args(args)
    tarzan.list_tarzan(
        in_fp, out_fp, args.blockstore_directory, password)


def do_extract(args, config):
    in_fp, out_fp = open_args(args)
    tarzan.filter_tarzan(
        in_fp, out_fp, args.blockstore_directory, password)


def main():
    args = tarzan.parse_args()
    config = tarzan.load_config_file(args.config_file)
    if args.keyfile is None and 'keyfile' in config:
        args.keyfile = config['keyfile']

    if args.command == 'genkey':
        do_genkey(args, config)
    if args.command == 'create':
        do_create(args, config)
    if args.command == 'decrypt':
        do_decrypt(args, config)
    if args.command == 'list':
        do_list(args, config)
    if args.command == 'extract':
        do_extract(args, config)

if __name__ == '__main__':
    main()
